countries_info = {
    "Afghanistan": {
        "Continent": "Asia",
        "Currency": "Afghan afghani (AFN)",
        "Languages": ["Dari", "Pashto"],
        "Cities": ["Kabul", "Herat", "Kandahar", "Mazar-i-Sharif", "Jalalabad"],
        "TimeZones": ["Afghanistan Time (AFT)"],
        "GMTOffSets": ["+4:30"],
        "IndependenceDate": "August 19, 1919",
        "Motto": "Strength through Unity",
        "GovernmentTypes": ["Islamic republic"]
    },
    "Albania": {
        "Continent": "Europe",
        "Currency": "Albanian lek (ALL)",
        "Languages": ["Albanian"],
        "Cities": ["Tirana", "Durrës", "Vlorë", "Fier", "Shkodër"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "November 28, 1912",
        "Motto": "Freedom and Justice",
        "GovernmentTypes": ["unitary parliamentary constitutional republic"]
    },
    "Algeria": {
        "Continent": "Africa",
        "Currency": "Algerian dinar (DZD)",
        "Languages": ["Arabic", "Berber"],
        "Cities": ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "July 5, 1962",
        "Motto": "By the People, For the People",
        "GovernmentTypes": ["presidential republic"]
    },
    "Andorra": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Catalan"],
        "Cities": ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "September 8, 1278",
        "Motto": "Virtus Unita Fortior",
        "GovernmentTypes": ["parliamentary co-principality"]
    },
    "Angola": {
        "Continent": "Africa",
        "Currency": "Angolan kwanza (AOA)",
        "Languages": ["Portuguese"],
        "Cities": ["Luanda", "N'dalatando", "Lubango", "Benguela", "Huambo"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "November 11, 1975",
        "Motto": "With Strength, We Will Achieve",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Antigua and Barbuda": {
        "Continent": "North America",
        "Currency": "East Caribbean dollar (XCD)",
        "Languages": ["English"],
        "Cities": ["Saint John's", "All Saints", "Liberta", "Potters Village", "Jolly Harbour"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "November 1, 1981",
        "Motto": "Each Endeavouring, All Achieving",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Argentina": {
        "Continent": "South America",
        "Currency": "Argentine peso (ARS)",
        "Languages": ["Spanish"],
        "Cities": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata"],
        "TimeZones": ["Argentina Time (ART)"],
        "GMTOffSets": ["-3"],
        "IndependenceDate": "May 25, 1810",
        "Motto": "In Union and Liberty",
        "GovernmentTypes": ["federal republic"]
    },
    "Armenia": {
        "Continent": "Asia",
        "Currency": "Armenian dram (AMD)",
        "Languages": ["Armenian"],
        "Cities": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan"],
        "TimeZones": ["Armenia Time (AMT)"],
        "GMTOffSets": ["+4"],
        "IndependenceDate": "September 21, 1991",
        "Motto": "A Nation, One Culture",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Australia": {
        "Continent": "Australia",
        "Currency": "Australian dollar (AUD)",
        "Languages": ["English"],
        "Cities": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
        "TimeZones": ["Australian Eastern Standard Time (AEST)"],
        "GMTOffSets": ["+10"],
        "IndependenceDate": "January 1, 1901",
        "Motto": "Advance Australia Fair",
        "GovernmentTypes": ["federal parliamentary constitutional monarchy"]
    },
    "Austria": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["German"],
        "Cities": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "October 26, 1955",
        "Motto": "United in Diversity",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "Azerbaijan": {
        "Continent": "Asia",
        "Currency": "Azerbaijani manat (AZN)",
        "Languages": ["Azerbaijani"],
        "Cities": ["Baku", "Ganja", "Sumqayit", "Lankaran", "Mingachevir"],
        "TimeZones": ["Azerbaijan Time (AZT)"],
        "GMTOffSets": ["+4"],
        "IndependenceDate": "October 18, 1991",
        "Motto": "The Land of Fire",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Bahamas": {
        "Continent": "North America",
        "Currency": "Bahamian dollar (BSD)",
        "Languages": ["English"],
        "Cities": ["Nassau", "Freeport", "West End", "Marsh Harbour", "Eleuthera"],
        "TimeZones": ["Eastern Standard Time (EST)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "July 10, 1973",
        "Motto": "Forward, Upward, Onward Together",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Bahrain": {
        "Continent": "Asia",
        "Currency": "Bahraini dinar (BHD)",
        "Languages": ["Arabic"],
        "Cities": ["Manama", "Muharraq", "Riffa", "Sitra", "Budaiya"],
        "TimeZones": ["Arabian Standard Time (AST)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "August 15, 1971",
        "Motto": "The Pearl of the Gulf",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Bangladesh": {
        "Continent": "Asia",
        "Currency": "Bangladeshi taka (BDT)",
        "Languages": ["Bengali"],
        "Cities": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
        "TimeZones": ["Bangladesh Standard Time (BST)"],
        "GMTOffSets": ["+6"],
        "IndependenceDate": "March 26, 1971",
        "Motto": "Unity is Strength",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Barbados": {
        "Continent": "North America",
        "Currency": "Barbadian dollar (BBD)",
        "Languages": ["English"],
        "Cities": ["Bridgetown", "Speightstown", "Oistins", "Holetown", "Bathsheba"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "November 30, 1966",
        "Motto": "Pride and Industry",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Belarus": {
        "Continent": "Europe",
        "Currency": "Belarusian ruble (BYN)",
        "Languages": ["Belarusian", "Russian"],
        "Cities": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Hrodna"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "July 3, 1990",
        "Motto": "We Are a Nation",
        "GovernmentTypes": ["presidential republic"]
    },
    "Belgium": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Dutch", "French", "German"],
        "Cities": ["Brussels", "Antwerp", "Ghent", "Bruges", "Namur"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "October 4, 1830",
        "Motto": "Unity Makes Strength",
        "GovernmentTypes": ["federal parliamentary constitutional monarchy"]
    },
    "Belize": {
        "Continent": "North America",
        "Currency": "Belize dollar (BZD)",
        "Languages": ["English"],
        "Cities": ["Belmopan", "Belize City", "San Ignacio", "Orange Walk Town", "Corozal Town"],
        "TimeZones": ["Central Standard Time (CST)"],
        "GMTOffSets": ["-6"],
        "IndependenceDate": "September 21, 1981",
        "Motto": "Sub Umbra",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Benin": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["French"],
        "Cities": ["Porto-Novo", "Cotonou", "Parakou", "Abomey", "Ouidah"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 1, 1960",
        "Motto": "Work, Justice, Progress",
        "GovernmentTypes": ["presidential republic"]
    },
    "Bhutan": {
        "Continent": "Asia",
        "Currency": "Bhutanese ngultrum (BTN)",
        "Languages": ["Dzongkha"],
        "Cities": ["Thimphu", "Phuntsholing", "Paro", "Jakar", "Gelephu"],
        "TimeZones": ["Bhutan Time (BTT)"],
        "GMTOffSets": ["+6"],
        "IndependenceDate": "N/A",
        "Motto": "Gross National Happiness",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Bolivia": {
        "Continent": "South America",
        "Currency": "Bolivian boliviano (BOB)",
        "Languages": ["Spanish", "Quechua", "Aymara"],
        "Cities": ["Sucre", "La Paz", "Santa Cruz", "El Alto", "Cochabamba"],
        "TimeZones": ["Bolivia Time (BOT)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "August 6, 1825",
        "Motto": "Unity, Liberty, Peace",
        "GovernmentTypes": ["unitary presidential constitutional republic"]
    },
    "Bosnia and Herzegovina": {
        "Continent": "Europe",
        "Currency": "Convertible mark (BAM)",
        "Languages": ["Bosnian", "Croatian", "Serbian"],
        "Cities": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "March 1, 1992",
        "Motto": "With Faith in God",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Botswana": {
        "Continent": "Africa",
        "Currency": "Botswana pula (BWP)",
        "Languages": ["English", "Tswana"],
        "Cities": ["Gaborone", "Francistown", "Molepolole", "Maun", "Kasane"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "September 30, 1966",
        "Motto": "Pula",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Brazil": {
        "Continent": "South America",
        "Currency": "Brazilian real (BRL)",
        "Languages": ["Portuguese"],
        "Cities": ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador", "Fortaleza"],
        "TimeZones": ["Brasilia Time (BRT)"],
        "GMTOffSets": ["-3"],
        "IndependenceDate": "September 7, 1822",
        "Motto": "Order and Progress",
        "GovernmentTypes": ["federal presidential republic"]
    },
    "Brunei": {
        "Continent": "Asia",
        "Currency": "Brunei dollar (BND)",
        "Languages": ["Malay"],
        "Cities": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar"],
        "TimeZones": ["Brunei Time (BNT)"],
        "GMTOffSets": ["+8"],
        "IndependenceDate": "January 1, 1984",
        "Motto": "Forever in Grace",
        "GovernmentTypes": ["absolute monarchy"]
    },
    "Bulgaria": {
        "Continent": "Europe",
        "Currency": "Bulgarian lev (BGN)",
        "Languages": ["Bulgarian"],
        "Cities": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "September 22, 1908",
        "Motto": "Unity Makes Strength",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Burkina Faso": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["French"],
        "Cities": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Manga", "Ouahigouya"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 5, 1960",
        "Motto": "Unity, Progress, Justice",
        "GovernmentTypes": ["presidential republic"]
    },
    "Burundi": {
        "Continent": "Africa",
        "Currency": "Burundian franc (BIF)",
        "Languages": ["Kirundi", "French", "English"],
        "Cities": ["Gitega", "Bujumbura", "Ngozi", "Muramvya", "Ruyigi"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "July 1, 1962",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["presidential republic"]
    },
    "Cabo Verde": {
        "Continent": "Africa",
        "Currency": "Cape Verdean escudo (CVE)",
        "Languages": ["Portuguese"],
        "Cities": ["Praia", "Mindelo", "Santa Maria", "Assomada", "Espargos"],
        "TimeZones": ["Cape Verde Time (CVT)"],
        "GMTOffSets": ["-1"],
        "IndependenceDate": "July 5, 1975",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Cambodia": {
        "Continent": "Asia",
        "Currency": "Cambodian riel (KHR)",
        "Languages": ["Khmer"],
        "Cities": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet"],
        "TimeZones": ["Indochina Time (ICT)"],
        "GMTOffSets": ["+7"],
        "IndependenceDate": "November 9, 1953",
        "Motto": "Nation, Religion, King",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Cameroon": {
        "Continent": "Africa",
        "Currency": "Central African CFA franc (XAF)",
        "Languages": ["English", "French"],
        "Cities": ["Yaoundé", "Douala", "Garoua", "Kumba", "Bamenda"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "January 1, 1960",
        "Motto": "Peace, Work, Fatherland",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Canada": {
        "Continent": "North America",
        "Currency": "Canadian dollar (CAD)",
        "Languages": ["English", "French"],
        "Cities": ["Ottawa", "Toronto", "Montreal", "Calgary", "Edmonton"],
        "TimeZones": ["Eastern Standard Time (EST)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "July 1, 1867",
        "Motto": "A Mari Usque Ad Mare",
        "GovernmentTypes": ["federal parliamentary constitutional monarchy"]
    },
    "Central African Republic": {
        "Continent": "Africa",
        "Currency": "Central African CFA franc (XAF)",
        "Languages": ["Sango", "French"],
        "Cities": ["Bangui", "Bimbo", "Berberati", "Mbaiki", "Bouar"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 13, 1960",
        "Motto": "Unity, Diligence, Progress",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Chad": {
        "Continent": "Africa",
        "Currency": "Central African CFA franc (XAF)",
        "Languages": ["French", "Arabic"],
        "Cities": ["N'Djamena", "Moundou", "Abéché", "Kelo", "Sarh"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 11, 1960",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["presidential republic"]
    },
    "Chile": {
        "Continent": "South America",
        "Currency": "Chilean peso (CLP)",
        "Languages": ["Spanish"],
        "Cities": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
        "TimeZones": ["Chile Standard Time (CLT)"],
        "GMTOffSets": ["-3"],
        "IndependenceDate": "September 18, 1810",
        "Motto": "By Reason or Force",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "China": {
        "Continent": "Asia",
        "Currency": "Renminbi (CNY)",
        "Languages": ["Mandarin"],
        "Cities": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu"],
        "TimeZones": ["China Standard Time (CST)"],
        "GMTOffSets": ["+8"],
        "IndependenceDate": "October 1, 1949",
        "Motto": "Get Rich Together",
        "GovernmentTypes": ["unitary one-party socialist republic"]
    },
    "Colombia": {
        "Continent": "South America",
        "Currency": "Colombian peso (COP)",
        "Languages": ["Spanish"],
        "Cities": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
        "TimeZones": ["Colombia Time (COT)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "July 20, 1810",
        "Motto": "Liberty and Order",
        "GovernmentTypes": ["unitary presidential constitutional republic"]
    },
    "Comoros": {
        "Continent": "Africa",
        "Currency": "Comorian franc (KMF)",
        "Languages": ["Comorian", "Arabic", "French"],
        "Cities": ["Moroni", "Moutsamoudou", "Domoni", "Fumbuni", "Dzaoudzi"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "July 6, 1975",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["federal presidential republic"]
    },
    "Republic of the Congo": {
        "Continent": "Africa",
        "Currency": "Central African CFA franc (XAF)",
        "Languages": ["French"],
        "Cities": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 15, 1960",
        "Motto": "Freedom, Equality, Brotherhood",
        "GovernmentTypes": ["presidential republic"]
    },
    "Congo DRC": {
        "Continent": "Africa",
        "Currency": "Congolese franc (CDF)",
        "Languages": ["French"],
        "Cities": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "June 30, 1960",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Costa Rica": {
        "Continent": "North America",
        "Currency": "Costa Rican colón (CRC)",
        "Languages": ["Spanish"],
        "Cities": ["San José", "Alajuela", "Cartago", "Heredia", "Guanacaste"],
        "TimeZones": ["Central Standard Time (CST)"],
        "GMTOffSets": ["-6"],
        "IndependenceDate": "September 15, 1821",
        "Motto": "Pura Vida",
        "GovernmentTypes": ["presidential republic"]
    },
    "Ivory Coast": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["French"],
        "Cities": ["Yamoussoukro", "Abidjan", "Bouaké", "Daloa", "San Pedro"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 7, 1960",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["presidential republic"]
    },
    "Croatia": {
        "Continent": "Europe",
        "Currency": "Croatian kuna (HRK)",
        "Languages": ["Croatian"],
        "Cities": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "June 25, 1991",
        "Motto": "Courage, Unity, Homeland",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Cuba": {
        "Continent": "North America",
        "Currency": "Cuban peso (CUP)",
        "Languages": ["Spanish"],
        "Cities": ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo"],
        "TimeZones": ["Cuba Standard Time (CST)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "May 20, 1902",
        "Motto": "Liberty or Death",
        "GovernmentTypes": ["unitary one-party socialist republic"]
    },
    "Cyprus": {
        "Continent": "Asia",
        "Currency": "Euro (EUR)",
        "Languages": ["Greek", "Turkish"],
        "Cities": ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "October 1, 1960",
        "Motto": "Eusios Aelios",
        "GovernmentTypes": ["presidential republic"]
    },
    "Czech Republic": {
        "Continent": "Europe",
        "Currency": "Czech koruna (CZK)",
        "Languages": ["Czech"],
        "Cities": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "January 1, 1993",
        "Motto": "Truth Prevails",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Denmark": {
        "Continent": "Europe",
        "Currency": "Danish krone (DKK)",
        "Languages": ["Danish"],
        "Cities": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "June 5, 1849",
        "Motto": "God's Help, The People's Love",
        "GovernmentTypes": ["unitary parliamentary constitutional monarchy"]
    },
    "Djibouti": {
        "Continent": "Africa",
        "Currency": "Djiboutian franc (DJF)",
        "Languages": ["French", "Arabic"],
        "Cities": ["Djibouti", "Ali Sabieh", "Tadjoura", "Dikhil", "Obock"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "June 27, 1977",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Dominica": {
        "Continent": "North America",
        "Currency": "East Caribbean dollar (XCD)",
        "Languages": ["English"],
        "Cities": ["Roseau", "Portsmouth", "Marigot", "Ladigue", "Berekua"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "November 3, 1978",
        "Motto": "After a Storm, There Is a Calm",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Dominican Republic": {
        "Continent": "North America",
        "Currency": "Dominican peso (DOP)",
        "Languages": ["Spanish"],
        "Cities": ["Santo Domingo", "Santiago de los Caballeros", "La Romana", "San Pedro de Macorís", "San Francisco de Macorís"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "February 27, 1844",
        "Motto": "God, Country, Freedom",
        "GovernmentTypes": ["presidential republic"]
    },
    "Ecuador": {
        "Continent": "South America",
        "Currency": "United States dollar (USD)",
        "Languages": ["Spanish"],
        "Cities": ["Quito", "Guayaquil", "Cuenca", "Machala", "Ambato"],
        "TimeZones": ["Ecuador Time (ECT)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "May 24, 1822",
        "Motto": "God, Country, Freedom",
        "GovernmentTypes": ["unitary presidential constitutional republic"]
    },
    "Egypt": {
        "Continent": "Africa",
        "Currency": "Egyptian pound (EGP)",
        "Languages": ["Arabic"],
        "Cities": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "February 28, 1922",
        "Motto": "The Nile is Life",
        "GovernmentTypes": ["unitary semi-presidential republic"]
    },
    "El Salvador": {
        "Continent": "North America",
        "Currency": "United States dollar (USD)",
        "Languages": ["Spanish"],
        "Cities": ["San Salvador", "Santa Ana", "San Miguel", "Mejicanos", "Apopa"],
        "TimeZones": ["Central Standard Time (CST)"],
        "GMTOffSets": ["-6"],
        "IndependenceDate": "September 15, 1821",
        "Motto": "God, Union, Freedom",
        "GovernmentTypes": ["presidential republic"]
    },
    "Equatorial Guinea": {
        "Continent": "Africa",
        "Currency": "Central African CFA franc (XAF)",
        "Languages": ["Spanish", "French", "Portuguese"],
        "Cities": ["Malabo", "Bata", "Ebebiyin", "Aconibe", "Evinayong"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "October 12, 1968",
        "Motto": "Unity, Peace, Justice",
        "GovernmentTypes": ["presidential republic"]
    },
    "Eritrea": {
        "Continent": "Africa",
        "Currency": "Nakfa (ERN)",
        "Languages": ["Tigrinya", "Arabic", "English"],
        "Cities": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "May 24, 1993",
        "Motto": "Unity, Peace, Justice",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Estonia": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Estonian"],
        "Cities": ["Tallinn", "Tartu", "Narva", "Kohtla-Järve", "Pärnu"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "February 24, 1918",
        "Motto": "One for All, All for One",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Eswatini": {
        "Continent": "Africa",
        "Currency": "Lilangeni (SZL)",
        "Languages": ["English", "siSwati"],
        "Cities": ["Mbabane", "Manzini", "Siteki", "Nhlangano", "Lobamba"],
        "TimeZones": ["South Africa Standard Time (SAST)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "September 6, 1968",
        "Motto": "Freedom, Integrity, Prosperity",
        "GovernmentTypes": ["absolute monarchy"]
    },
    "Ethiopia": {
        "Continent": "Africa",
        "Currency": "Ethiopian birr (ETB)",
        "Languages": ["Amharic"],
        "Cities": ["Addis Ababa", "Gondar", "Mekele", "Dire Dawa", "Adama"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "N/A",
        "Motto": "Power, Unity, Freedom",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "Fiji": {
        "Continent": "Oceania",
        "Currency": "Fijian dollar (FJD)",
        "Languages": ["English", "Fijian", "Hindi"],
        "Cities": ["Suva", "Nadi", "Lautoka", "Labasa", "Ba"],
        "TimeZones": ["Fiji Time (FJT)"],
        "GMTOffSets": ["+12"],
        "IndependenceDate": "October 10, 1970",
        "Motto": "Rerevaka na Kalou ka Doka na Tui",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Finland": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Finnish", "Swedish"],
        "Cities": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "December 6, 1917",
        "Motto": "The Land of a Thousand Lakes",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "France": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["French"],
        "Cities": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "September 24, 843",
        "Motto": "Liberty, Equality, Fraternity",
        "GovernmentTypes": ["unitary semi-presidential republic"]
    },
    "Gabon": {
        "Continent": "Africa",
        "Currency": "Central African CFA franc (XAF)",
        "Languages": ["French"],
        "Cities": ["Libreville", "Port-Gentil", "Franceville", "Moanda", "Oyem"],
        "TimeZones": ["Gabon Time (GAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 16, 1960",
        "Motto": "Unity, Work, Justice",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Gambia": {
        "Continent": "Africa",
        "Currency": "Dalasi (GMD)",
        "Languages": ["English"],
        "Cities": ["Banjul", "Serekunda", "Brikama", "Bakau", "Lamin"],
        "TimeZones": ["Gambia Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "February 18, 1965",
        "Motto": "Progress, Peace, Prosperity",
        "GovernmentTypes": ["presidential republic"]
    },
    "Georgia": {
        "Continent": "Asia",
        "Currency": "Lari (GEL)",
        "Languages": ["Georgian"],
        "Cities": ["Tbilisi", "Batumi", "Rustavi", "Zugdidi", "Zestafoni"],
        "TimeZones": ["Georgia Standard Time (GET)"],
        "GMTOffSets": ["+4"],
        "IndependenceDate": "April 9, 1991",
        "Motto": "Freedom, National Unity",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Germany": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["German"],
        "Cities": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "January 1, 1871",
        "Motto": "Unity and Justice and Freedom",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "Ghana": {
        "Continent": "Africa",
        "Currency": "Ghanaian cedi (GHS)",
        "Languages": ["English"],
        "Cities": ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman"],
        "TimeZones": ["Ghana Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "March 6, 1957",
        "Motto": "Freedom and Justice",
        "GovernmentTypes": ["presidential republic"]
    },
    "Greece": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Greek"],
        "Cities": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "March 25, 1821",
        "Motto": "Freedom or Death",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Grenada": {
        "Continent": "North America",
        "Currency": "East Caribbean dollar (XCD)",
        "Languages": ["English"],
        "Cities": ["St. George's", "Gouyave", "Grenville", "Victoria", "Sauteurs"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "February 7, 1974",
        "Motto": "The Land of Spice",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Guatemala": {
        "Continent": "North America",
        "Currency": "Guatemalan quetzal (GTQ)",
        "Languages": ["Spanish"],
        "Cities": ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "San Juan Sacatepéquez"],
        "TimeZones": ["Central Standard Time (CST)"],
        "GMTOffSets": ["-6"],
        "IndependenceDate": "September 15, 1821",
        "Motto": "Liberty 27 and Independence",
        "GovernmentTypes": ["presidential republic"]
    },
    "Guinea": {
        "Continent": "Africa",
        "Currency": "Guinean franc (GNF)",
        "Languages": ["French"],
        "Cities": ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé"],
        "TimeZones": ["Greenwich Mean Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "October 2, 1958",
        "Motto": "Work, Justice, Solidarity",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Guinea-Bissau": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["Portuguese"],
        "Cities": ["Bissau", "Bolama", "Cacheu", "Gambie", "Bafatá"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "September 24, 1973",
        "Motto": "Unity, Struggle, Progress",
        "GovernmentTypes": ["presidential republic"]
    },
    "Guyana": {
        "Continent": "South America",
        "Currency": "Guyanese dollar (GYD)",
        "Languages": ["English"],
        "Cities": ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica"],
        "TimeZones": ["Guyana Time (GYT)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "May 26, 1966",
        "Motto": "One People, One Nation, One Destiny",
        "GovernmentTypes": ["presidential republic"]
    },
    "Haiti": {
        "Continent": "North America",
        "Currency": "Gourde (HTG)",
        "Languages": ["Haitian Creole", "French"],
        "Cities": ["Port-au-Prince", "Cap-Haïtien", "Les Cayes", "Pétion-Ville", "Jacmel"],
        "TimeZones": ["Haiti Time (HT)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "January 1, 1804",
        "Motto": "Liberty, Equality, Fraternity",
        "GovernmentTypes": ["semi-presidential republic"]
    },
    "Honduras": {
        "Continent": "North America",
        "Currency": "Lempira (HNL)",
        "Languages": ["Spanish"],
        "Cities": ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma", "El Progreso"],
        "TimeZones": ["Central Standard Time (CST)"],
        "GMTOffSets": ["-6"],
        "IndependenceDate": "September 15, 1821",
        "Motto": "Free, Sovereign, Independent",
        "GovernmentTypes": ["presidential republic"]
    },
    "Hungary": {
        "Continent": "Europe",
        "Currency": "Hungarian forint (HUF)",
        "Languages": ["Hungarian"],
        "Cities": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 20, 1000",
        "Motto": "With God's Help",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Iceland": {
        "Continent": "Europe",
        "Currency": "Icelandic króna (ISK)",
        "Languages": ["Icelandic"],
        "Cities": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri", "Akranes"],
        "TimeZones": ["Greenwich Mean Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "June 17, 1944",
        "Motto": "Eternal Flame",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "India": {
        "Continent": "Asia",
        "Currency": "Indian rupee (INR)",
        "Languages": ["Hindi", "English"],
        "Cities": ["Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai"],
        "TimeZones": ["Indian Standard Time (IST)"],
        "GMTOffSets": ["+5:30"],
        "IndependenceDate": "August 15, 1947",
        "Motto": "Truth Alone Triumphs",
        "GovernmentTypes": ["federal parliamentary democratic republic"]
    },
    "Indonesia": {
        "Continent": "Asia",
        "Currency": "Indonesian rupiah (IDR)",
        "Languages": ["Indonesian"],
        "Cities": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
        "TimeZones": ["Western Indonesia Time (WIB)"],
        "GMTOffSets": ["+7"],
        "IndependenceDate": "August 17, 1945",
        "Motto": "Unity in Diversity",
        "GovernmentTypes": ["presidential republic"]
    },
    "Iran": {
        "Continent": "Asia",
        "Currency": "Iranian rial (IRR)",
        "Languages": ["Persian"],
        "Cities": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz"],
        "TimeZones": ["Iran Standard Time (IRST)"],
        "GMTOffSets": ["+3:30"],
        "IndependenceDate": "N/A",
        "Motto": "Independence, Freedom, Islamic Republic",
        "GovernmentTypes": ["Islamic republic"]
    },
    "Iraq": {
        "Continent": "Asia",
        "Currency": "Iraqi dinar (IQD)",
        "Languages": ["Arabic", "Kurdish"],
        "Cities": ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah"],
        "TimeZones": ["Arabian Standard Time (AST)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "October 3, 1932",
        "Motto": "By the People, For the People",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "Ireland": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Irish", "English"],
        "Cities": ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
        "TimeZones": ["Greenwich Mean Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "April 24, 1916",
        "Motto": "Éire go Brách",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Israel": {
        "Continent": "Asia",
        "Currency": "Israeli new shekel (ILS)",
        "Languages": ["Hebrew", "Arabic"],
        "Cities": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
        "TimeZones": ["Israel Standard Time (IST)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "May 14, 1948",
        "Motto": "The People of Israel Live",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Italy": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Italian"],
        "Cities": ["Rome", "Milan", "Naples", "Turin", "Palermo"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "March 17, 1861",
        "Motto": "Unity and Love",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Jamaica": {
        "Continent": "North America",
        "Currency": "Jamaican dollar (JMD)",
        "Languages": ["English"],
        "Cities": ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "Mandeville"],
        "TimeZones": ["Eastern Standard Time (EST)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "August 6, 1962",
        "Motto": "Out of Many, One People",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Japan": {
        "Continent": "Asia",
        "Currency": "Yen (JPY)",
        "Languages": ["Japanese"],
        "Cities": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo"],
        "TimeZones": ["Japan Standard Time (JST)"],
        "GMTOffSets": ["+9"],
        "IndependenceDate": "N/A",
        "Motto": "Harmony and Peace",
        "GovernmentTypes": ["unitary parliamentary constitutional monarchy"]
    },
    "Jordan": {
        "Continent": "Asia",
        "Currency": "Jordanian dinar (JOD)",
        "Languages": ["Arabic"],
        "Cities": ["Amman", "Zarqa", "Irbid", "Russeifa", "Ajloun"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "May 25, 1946",
        "Motto": "God, Country, King",
        "GovernmentTypes": ["unitary parliamentary constitutional monarchy"]
    },
    "Kazakhstan": {
        "Continent": "Asia",
        "Currency": "Tenge (KZT)",
        "Languages": ["Kazakh", "Russian"],
        "Cities": ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe"],
        "TimeZones": ["Kazakhstan Time (ALMT)"],
        "GMTOffSets": ["+6"],
        "IndependenceDate": "December 16, 1991",
        "Motto": "I Believe in Kazakhstan",
        "GovernmentTypes": ["presidential republic"]
    },
    "Kenya": {
        "Continent": "Africa",
        "Currency": "Kenyan shilling (KES)",
        "Languages": ["Swahili", "English"],
        "Cities": ["Nairobi", "Mombasa", "Nakuru", "Eldoret", "Kisumu"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "December 12, 1963",
        "Motto": "Unity, Peace, Freedom",
        "GovernmentTypes": ["presidential republic"]
    },
    "Kiribati": {
        "Continent": "Oceania",
        "Currency": "Australian dollar (AUD)",
        "Languages": ["Gilbertese", "English"],
        "Cities": ["South Tarawa", "Betio", "Buariki", "Teaoraereke", "Nanikai"],
        "TimeZones": ["Gilbert Islands Time (GILT)"],
        "GMTOffSets": ["+12"],
        "IndependenceDate": "July 12, 1979",
        "Motto": "Peace, Unity, Freedom",
        "GovernmentTypes": ["presidential republic"]
    },
    "Kuwait": {
        "Continent": "Asia",
        "Currency": "Kuwaiti dinar (KWD)",
        "Languages": ["Arabic"],
        "Cities": ["Kuwait City", "Al Ahmadi", "Hawalli", "Salmiya", "Fahaheel"],
        "TimeZones": ["Arabian Standard Time (AST)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "June 19, 1961",
        "Motto": "Freedom, Independence, Peace",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Kyrgyzstan": {
        "Continent": "Asia",
        "Currency": "Som (KGS)",
        "Languages": ["Kyrgyz", "Russian"],
        "Cities": ["Bishkek", "Osh", "Jalal-Abad", "Talas", "Naryn"],
        "TimeZones": ["Kyrgyzstan Time (KGT)"],
        "GMTOffSets": ["+6"],
        "IndependenceDate": "August 31, 1991",
        "Motto": "Unity is Our Strength",
        "GovernmentTypes": ["presidential republic"]
    },
    "Laos": {
        "Continent": "Asia",
        "Currency": "Lao kip (LAK)",
        "Languages": ["Lao"],
        "Cities": ["Vientiane", "Luang Prabang", "Pakse", "Savannakhet", "Thakhek"],
        "TimeZones": ["Indochina Time (ICT)"],
        "GMTOffSets": ["+7"],
        "IndependenceDate": "July 19, 1949",
        "Motto": "Peace, Independence, Democracy",
        "GovernmentTypes": ["socialist republic"]
    },
    "Latvia": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Latvian"],
        "Cities": ["Riga", "Daugavpils", "Liepāja", "Jūrmala", "Rēzekne"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "November 18, 1918",
        "Motto": "For the Fatherland and Freedom",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Lebanon": {
        "Continent": "Asia",
        "Currency": "Lebanese pound (LBP)",
        "Languages": ["Arabic", "French"],
        "Cities": ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "November 22, 1943",
        "Motto": "All for the Country",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Lesotho": {
        "Continent": "Africa",
        "Currency": "Lesotho loti (LSL)",
        "Languages": ["Sesotho", "English"],
        "Cities": ["Maseru", "Teyateyaneng", "Leribe", "Maputsoe", "Qacha's Nek"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "October 4, 1966",
        "Motto": "Peace, Rain, Prosperity",
        "GovernmentTypes": ["parliamentary constitutional monarchy"]
    },
    "Liberia": {
        "Continent": "Africa",
        "Currency": "Liberian dollar (LRD)",
        "Languages": ["English"],
        "Cities": ["Monrovia", "Gbarnga", "Buchanan", "Kakata", "Harper"],
        "TimeZones": ["Greenwich Mean Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "July 26, 1847",
        "Motto": "The Love of Liberty Brought Us Here",
        "GovernmentTypes": ["presidential republic"]
    },
    "Libya": {
        "Continent": "Africa",
        "Currency": "Libyan dinar (LYD)",
        "Languages": ["Arabic"],
        "Cities": ["Tripoli", "Benghazi", "Misrata", "Zliten", "Al Khums"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "December 24, 1951",
        "Motto": "Freedom, Justice, Peace",
        "GovernmentTypes": ["unified transitional government"]
    },
    "Liechtenstein": {
        "Continent": "Europe",
        "Currency": "Swiss franc (CHF)",
        "Languages": ["German"],
        "Cities": ["Vaduz", "Schaan", "Balzers", "Eschen", "Gamprin"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "January 23, 1719",
        "Motto": "For God, For Country",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Lithuania": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Lithuanian"],
        "Cities": ["Vilnius", "Kaunas", "Klaipeda", "Šiauliai", "Panevėžys"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "February 16, 1918",
        "Motto": "For the Fatherland",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Luxembourg": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Luxembourgish", "French", "German"],
        "Cities": ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Echternach"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "June 23, 1890",
        "Motto": "We Want to Remain What We Are",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Madagascar": {
        "Continent": "Africa",
        "Currency": "Malagasy ariary (MGA)",
        "Languages": ["Malagasy", "French"],
        "Cities": ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "June 26, 1960",
        "Motto": "Unity, Focusing on Our Future",
        "GovernmentTypes": ["semi-presidential republic"]
    },
    "Malawi": {
        "Continent": "Africa",
        "Currency": "Malawian kwacha (MWK)",
        "Languages": ["English", "Chichewa"],
        "Cities": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "July 6, 1964",
        "Motto": "Unity and Freedom",
        "GovernmentTypes": ["presidential republic"]
    },
    "Malaysia": {
        "Continent": "Asia",
        "Currency": "Malaysian ringgit (MYR)",
        "Languages": ["Malay"],
        "Cities": ["Kuala Lumpur", "George Town", "Johor Bahru", "Kota Kinabalu", "Malacca Town"],
        "TimeZones": ["Malaysia Standard Time (MYT)"],
        "GMTOffSets": ["+8"],
        "IndependenceDate": "August 31, 1957",
        "Motto": "Unity is Strength",
        "GovernmentTypes": ["federal constitutional monarchy"]
    },
    "Maldives": {
        "Continent": "Asia",
        "Currency": "Maldivian rufiyaa (MVR)",
        "Languages": ["Dhivehi"],
        "Cities": ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Dhidhdhoo"],
        "TimeZones": ["Maldives Time (MVT)"],
        "GMTOffSets": ["+5"],
        "IndependenceDate": "July 26, 1965",
        "Motto": "Unity is Strength",
        "GovernmentTypes": ["presidential republic"]
    },
    "Mali": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["French"],
        "Cities": ["Bamako", "Segou", "Koutiala", "Kayes", "Mopti"],
        "TimeZones": ["Ghana Mean Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "September 22, 1960",
        "Motto": "One People, One Goal, One Faith",
        "GovernmentTypes": ["transitional government"]
    },
    "Malta": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Maltese", "English"],
        "Cities": ["Valletta", "Birkirkara", "Sliema", "Qormi", "Senglea"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "September 21, 1964",
        "Motto": "The Sea is Our Life",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Marshall Islands": {
        "Continent": "Oceania",
        "Currency": "United States dollar (USD)",
        "Languages": ["Marshallese", "English"],
        "Cities": ["Majuro", "Ebeye", "Laura", "Ailinglaplap", "Maloelap"],
        "TimeZones": ["Marshall Islands Time (MHT)"],
        "GMTOffSets": ["+12"],
        "IndependenceDate": "May 1, 1979",
        "Motto": "Land of the Free",
        "GovernmentTypes": ["presidential republic"]
    },
    "Mauritania": {
        "Continent": "Africa",
        "Currency": "Ouguiya (MRU)",
        "Languages": ["Arabic"],
        "Cities": ["Nouakchott", "Nouadhibou", "Rosso", "Kiffa", "Kaedi"],
        "TimeZones": ["Greenwich Mean Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "November 28, 1960",
        "Motto": "Honor and Faith",
        "GovernmentTypes": ["presidential republic"]
    },
    "Mauritius": {
        "Continent": "Africa",
        "Currency": "Mauritian rupee (MUR)",
        "Languages": ["English", "French"],
        "Cities": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes"],
        "TimeZones": ["Mauritius Standard Time (MUT)"],
        "GMTOffSets": ["+4"],
        "IndependenceDate": "March 12, 1968",
        "Motto": "Strengthen Our Unity",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Mexico": {
        "Continent": "North America",
        "Currency": "Mexican peso (MXN)",
        "Languages": ["Spanish"],
        "Cities": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
        "TimeZones": ["Central Standard Time (CST)"],
        "GMTOffSets": ["-6"],
        "IndependenceDate": "September 16, 1810",
        "Motto": "Land of the Free",
        "GovernmentTypes": ["federal republic"]
    },
    "Micronesia": {
        "Continent": "Oceania",
        "Currency": "United States dollar (USD)",
        "Languages": ["English"],
        "Cities": ["Palikir", "Weno", "Kolonia", "Tamuning", "Chuuk"],
        "TimeZones": ["Chamorro Standard Time (ChST)"],
        "GMTOffSets": ["+10"],
        "IndependenceDate": "November 3, 1986",
        "Motto": "Peace, Unity, Liberty",
        "GovernmentTypes": ["federal republic"]
    },
    "Moldova": {
        "Continent": "Europe",
        "Currency": "Moldovan leu (MDL)",
        "Languages": ["Romanian"],
        "Cities": ["Chișinău", "Bălți", "Bender", "Rîbnița", "Cahul"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "August 27, 1991",
        "Motto": "The Land of Plenty",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Monaco": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["French"],
        "Cities": ["Monaco", "Monte Carlo", "La Condamine", "Moneghetti", "Fontvieille"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "January 8, 1297",
        "Motto": "Regnum eorum non praescriptum",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Mongolia": {
        "Continent": "Asia",
        "Currency": "Mongolian tögrög (MNT)",
        "Languages": ["Mongolian"],
        "Cities": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön"],
        "TimeZones": ["Ulaanbaatar Time (ULAT)"],
        "GMTOffSets": ["+8"],
        "IndependenceDate": "July 11, 1921",
        "Motto": "The Land of Blue Sky",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Montenegro": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Montenegrin"],
        "Cities": ["Podgorica", "Nikšić", "Herceg Novi", "Bijelo Polje", "Pljevlja"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "June 3, 2006",
        "Motto": "With Faith in God",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Morocco": {
        "Continent": "Africa",
        "Currency": "Moroccan dirham (MAD)",
        "Languages": ["Arabic", "Berber"],
        "Cities": ["Casablanca", "Rabat", "Marrakech", "Fes", "Tangier"],
        "TimeZones": ["Western European Time (WET)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "March 2, 1956",
        "Motto": "God, Country, King",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Mozambique": {
        "Continent": "Africa",
        "Currency": "Mozambican metical (MZN)",
        "Languages": ["Portuguese"],
        "Cities": ["Maputo", "Beira", "Nampula", "Quelimane", "Tete"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "June 25, 1975",
        "Motto": "Unity, Work, Victory",
        "GovernmentTypes": ["presidential republic"]
    },
    "Myanmar": {
        "Continent": "Asia",
        "Currency": "Kyat (MMK)",
        "Languages": ["Burmese"],
        "Cities": ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine", "Minbu"],
        "TimeZones": ["Myanmar Time (MMT)"],
        "GMTOffSets": ["+6:30"],
        "IndependenceDate": "January 4, 1948",
        "Motto": "Peace, Independence, Democracy",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Namibia": {
        "Continent": "Africa",
        "Currency": "Namibian dollar (NAD)",
        "Languages": ["English"],
        "Cities": ["Windhoek", "Walvis Bay", "Swakopmund", "Oshakati", "Rundu"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "March 21, 1990",
        "Motto": "Unity is Strength",
        "GovernmentTypes": ["presidential republic"]
    },
    "Nauru": {
        "Continent": "Oceania",
        "Currency": "Australian dollar (AUD)",
        "Languages": ["Nauruan", "English"],
        "Cities": ["Yaren", "Meneng", "Boer", "Denigomodu", "Nauru"],
        "TimeZones": ["Nauru Time (NRT)"],
        "GMTOffSets": ["+12"],
        "IndependenceDate": "January 31, 1968",
        "Motto": "God's Will First",
        "GovernmentTypes": ["presidential republic"]
    },
    "Nepal": {
        "Continent": "Asia",
        "Currency": "Nepalese rupee (NPR)",
        "Languages": ["Nepali"],
        "Cities": ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bhaktapur"],
        "TimeZones": ["Nepal Time (NPT)"],
        "GMTOffSets": ["+5:45"],
        "IndependenceDate": "September 1, 1768",
        "Motto": "Unity in Diversity",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "Netherlands": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Dutch"],
        "Cities": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "April 16, 1579",
        "Motto": "Je maintiendrai",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "New Zealand": {
        "Continent": "Oceania",
        "Currency": "New Zealand dollar (NZD)",
        "Languages": ["English", "Māori", "New Zealand Sign Language"],
        "Cities": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
        "TimeZones": ["New Zealand Standard Time (NZST)"],
        "GMTOffSets": ["+12"],
        "IndependenceDate": "September 26, 1907",
        "Motto": "He Waka Eke Noa",
        "GovernmentTypes": ["parliamentary representative democratic republic"]
    },
    "Nicaragua": {
        "Continent": "North America",
        "Currency": "Nicaraguan córdoba (NIO)",
        "Languages": ["Spanish"],
        "Cities": ["Managua", "León", "Masaya", "Granada", "Estelí"],
        "TimeZones": ["Central Standard Time (CST)"],
        "GMTOffSets": ["-6"],
        "IndependenceDate": "September 15, 1821",
        "Motto": "In God We Trust",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Niger": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["French"],
        "Cities": ["Niamey", "Zinder", "Maradi", "Aguie", "Diffa"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 3, 1960",
        "Motto": "Unity, Work, Progress",
        "GovernmentTypes": ["presidential republic"]
    },
    "Nigeria": {
        "Continent": "Africa",
        "Currency": "Nigerian naira (NGN)",
        "Languages": ["English"],
        "Cities": ["Lagos", "Abuja", "Port Harcourt", "Ibadan", "Kano"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "October 1, 1960",
        "Motto": "Unity and Faith, Peace and Progress",
        "GovernmentTypes": ["federal presidential republic"]
    },
    "North Korea": {
        "Continent": "Asia",
        "Currency": "North Korean won (KPW)",
        "Languages": ["Korean"],
        "Cities": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan"],
        "TimeZones": ["Pyongyang Time (PYT)"],
        "GMTOffSets": ["+9"],
        "IndependenceDate": "September 9, 1948",
        "Motto": "Powerful and Prosperous Nation",
        "GovernmentTypes": ["single-party state", "totalitarian dictatorship"]
    },
    "North Macedonia": {
        "Continent": "Europe",
        "Currency": "Macedonian denar (MKD)",
        "Languages": ["Macedonian"],
        "Cities": ["Skopje", "Bitola", "Kumanovo", "Ohrid", "Tetovo"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "September 8, 1991",
        "Motto": "Unity is Strength",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Norway": {
        "Continent": "Europe",
        "Currency": "Norwegian krone (NOK)",
        "Languages": ["Norwegian"],
        "Cities": ["Oslo", "Bergen", "Stavanger", "Drammen", "Kristiansand"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "May 17, 1814",
        "Motto": "Alt for Norge",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Oman": {
        "Continent": "Asia",
        "Currency": "Omani rial (OMR)",
        "Languages": ["Arabic"],
        "Cities": ["Muscat", "Salalah", "Sohar", "Bawshar", "Ibri"],
        "TimeZones": ["Gulf Standard Time (GST)"],
        "GMTOffSets": ["+4"],
        "IndependenceDate": "November 18, 1650",
        "Motto": "We Obey You",
        "GovernmentTypes": ["absolute monarchy"]
    },
    "Pakistan": {
        "Continent": "Asia",
        "Currency": "Pakistani rupee (PKR)",
        "Languages": ["Urdu", "English"],
        "Cities": ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi"],
        "TimeZones": ["Pakistan Standard Time (PKT)"],
        "GMTOffSets": ["+5"],
        "IndependenceDate": "August 14, 1947",
        "Motto": "Faith, Unity, Discipline",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "Palau": {
        "Continent": "Oceania",
        "Currency": "United States dollar (USD)",
        "Languages": ["Palauan", "English"],
        "Cities": ["Ngerulmud", "Melekeok", "Koror", "Airai", "Ngaraard"],
        "TimeZones": ["Palau Time (PALT)"],
        "GMTOffSets": ["+9"],
        "IndependenceDate": "October 1, 1994",
        "Motto": "The Land of the Free",
        "GovernmentTypes": ["presidential republic"]
    },
    "Panama": {
        "Continent": "North America",
        "Currency": "Panamanian balboa (PAB), United States dollar (USD)",
        "Languages": ["Spanish"],
        "Cities": ["Panama City", "San Miguelito", "David", "Colón", "Santiago"],
        "TimeZones": ["Eastern Standard Time (EST)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "November 3, 1903",
        "Motto": "For the Benefit of the World",
        "GovernmentTypes": ["presidential constitutional republic"]
    },
    "Papua New Guinea": {
        "Continent": "Oceania",
        "Currency": "Papua New Guinean kina (PGK)",
        "Languages": ["Tok Pisin", "Hiri Motu", "English"],
        "Cities": ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Goroka"],
        "TimeZones": ["Papua New Guinea Time (PGT)"],
        "GMTOffSets": ["+10"],
        "IndependenceDate": "September 16, 1975",
        "Motto": "Unity in Diversity",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Paraguay": {
        "Continent": "South America",
        "Currency": "Paraguayan guaraní (PYG)",
        "Languages": ["Spanish", "Guaraní"],
        "Cities": ["Asunción", "Ciudad del Este", "Encarnación", "Concepción", "Luque"],
        "TimeZones": ["Paraguay Standard Time (PYT)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "May 14, 1811",
        "Motto": "Peace and Justice",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Peru": {
        "Continent": "South America",
        "Currency": "Peruvian sol (PEN)",
        "Languages": ["Spanish", "Quechua", "Aymara"],
        "Cities": ["Lima", "Arequipa", "Trujillo", "Callao", "Chiclayo"],
        "TimeZones": ["Peru Time (PET)"],
        "GMTOffSets": ["-5"],
        "IndependenceDate": "July 28, 1821",
        "Motto": "Firme y Feliz por la Unión",
        "GovernmentTypes": ["unitary presidential constitutional republic"]
    },
    "Philippines": {
        "Continent": "Asia",
        "Currency": "Philippine peso (PHP)",
        "Languages": ["Filipino", "English"],
        "Cities": ["Quezon City", "Manila", "Davao City", "Cebu City", "Zamboanga City"],
        "TimeZones": ["Philippine Time (PHT)"],
        "GMTOffSets": ["+8"],
        "IndependenceDate": "June 12, 1898",
        "Motto": "National Unity",
        "GovernmentTypes": ["unitary presidential constitutional republic"]
    },
    "Poland": {
        "Continent": "Europe",
        "Currency": "Polish złoty (PLN)",
        "Languages": ["Polish"],
        "Cities": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "November 11, 1918",
        "Motto": "For our freedom and yours",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Portugal": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Portuguese"],
        "Cities": ["Lisbon", "Porto", "Amadora", "Braga", "Coimbra"],
        "TimeZones": ["Western European Time (WET)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "October 5, 1143",
        "Motto": "A Faithful People",
        "GovernmentTypes": ["unitary semi-presidential republic"]
    },
    "Qatar": {
        "Continent": "Asia",
        "Currency": "Qatari riyal (QAR)",
        "Languages": ["Arabic"],
        "Cities": ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal Mohammed"],
        "TimeZones": ["Arabian Standard Time (AST)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "September 3, 1971",
        "Motto": "All for Qatar",
        "GovernmentTypes": ["absolute monarchy"]
    },
    "Romania": {
        "Continent": "Europe",
        "Currency": "Romanian leu (RON)",
        "Languages": ["Romanian"],
        "Cities": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "May 9, 1877",
        "Motto": "Unity in Diversity",
        "GovernmentTypes": ["semi-presidential republic"]
    },
    "Russia": {
        "Continent": "Europe",
        "Currency": "Russian ruble (RUB)",
        "Languages": ["Russian"],
        "Cities": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Nizhny Novgorod"],
        "TimeZones": ["Moscow Standard Time (MSK)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "June 12, 1990",
        "Motto": "For Faith, Tsar and Fatherland",
        "GovernmentTypes": ["federal semi-presidential republic"]
    },
    "Rwanda": {
        "Continent": "Africa",
        "Currency": "Rwandan franc (RWF)",
        "Languages": ["Kinyarwanda", "French", "English"],
        "Cities": ["Kigali", "Butare", "Gisenyi", "Musanze", "Nyamata"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "July 1, 1962",
        "Motto": "Unity, Work, Patriotism",
        "GovernmentTypes": ["presidential republic"]
    },
    "Saint Kitts and Nevis": {
        "Continent": "North America",
        "Currency": "East Caribbean dollar (XCD)",
        "Languages": ["English"],
        "Cities": ["Basseterre", "Charlestown", "Tabernacle", "Bambarra", "Cayon"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "September 19, 1983",
        "Motto": "Together We as One",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "Saint Lucia": {
        "Continent": "North America",
        "Currency": "East Caribbean dollar (XCD)",
        "Languages": ["English"],
        "Cities": ["Castries", "Vieux Fort", "Soufrière", "Bisee", "Gros Islet"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "February 22, 1979",
        "Motto": "The Land, The People, The Light",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Saint Vincent and the Grenadines": {
        "Continent": "North America",
        "Currency": "East Caribbean dollar (XCD)",
        "Languages": ["English"],
        "Cities": ["Kingstown", "Calliaqua", "Chateaubelair", "Georgetown", "Bequia"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "October 27, 1979",
        "Motto": "The Land of the Free",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Samoa": {
        "Continent": "Oceania",
        "Currency": "Samoan tala (WST)",
        "Languages": ["Samoan", "English"],
        "Cities": ["Apia", "A'ana", "Aiga-i-le-Tai", "Atua", "Fa'asaleleaga"],
        "TimeZones": ["Samoa Standard Time (WST)"],
        "GMTOffSets": ["+13"],
        "IndependenceDate": "January 1, 1962",
        "Motto": "The Land of the Free",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "San Marino": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Italian"],
        "Cities": ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "September 3, 301",
        "Motto": "Libertas",
        "GovernmentTypes": ["diarchy"]
    },
    "Sao Tome and Principe": {
        "Continent": "Africa",
        "Currency": "Dobra (STN)",
        "Languages": ["Portuguese"],
        "Cities": ["São Tomé", "Trindade", "Neves", "Santana", "Guadalupe"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "July 12, 1975",
        "Motto": "Unity, Discipline, Work",
        "GovernmentTypes": ["unitary semi-presidential republic"]
    },
    "Saudi Arabia": {
        "Continent": "Asia",
        "Currency": "Saudi riyal (SAR)",
        "Languages": ["Arabic"],
        "Cities": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
        "TimeZones": ["Arabian Standard Time (AST)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "September 23, 1932",
        "Motto": "There is no god but Allah; Muhammad is his prophet",
        "GovernmentTypes": ["absolute monarchy"]
    },
    "Senegal": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["French"],
        "Cities": ["Dakar", "Touba", "Pikine", "Thiès", "Ziguinchor"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "April 4, 1960",
        "Motto": "One People, One Goal",
        "GovernmentTypes": ["semi-presidential republic"]
    },
    "Serbia": {
        "Continent": "Europe",
        "Currency": "Serbian dinar (RSD)",
        "Languages": ["Serbian"],
        "Cities": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "February 15, 1835",
        "Motto": "Only Unity Saves the Serbs",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Seychelles": {
        "Continent": "Africa",
        "Currency": "Seychellois rupee (SCR)",
        "Languages": ["Seychellois Creole", "English", "French"],
        "Cities": ["Victoria", "Beau Vallon", "Anse Boileau", "Anse Royale", "Baie Sainte Anne"],
        "TimeZones": ["Seychelles Time (SCT)"],
        "GMTOffSets": ["+4"],
        "IndependenceDate": "June 29, 1976",
        "Motto": "Faith and Works",
        "GovernmentTypes": ["presidential republic"]
    },
    "Sierra Leone": {
        "Continent": "Africa",
        "Currency": "Sierra Leonean leone (SLL)",
        "Languages": ["English"],
        "Cities": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
        "TimeZones": ["Greenwich Mean Time (GMT)"],
        "GMTOffSets": ["0"],
        "IndependenceDate": "April 27, 1961",
        "Motto": "For All Together",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Singapore": {
        "Continent": "Asia",
        "Currency": "Singapore dollar (SGD)",
        "Languages": ["English", "Malay", "Mandarin", "Tamil"],
        "Cities": ["Singapore", "Jurong East", "Tampines", "Woodlands", "Yishun"],
        "TimeZones": ["Singapore Standard Time (SGT)"],
        "GMTOffSets": ["+8"],
        "IndependenceDate": "August 9, 1965",
        "Motto": "Majulah Singapura (Onward Singapore)",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Slovakia": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Slovak"],
        "Cities": ["Bratislava", "Košice", "Prešov", "Nitra", "Trnava"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "January 1, 1993",
        "Motto": "Truth prevails",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Slovenia": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Slovene"],
        "Cities": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "June 25, 1991",
        "Motto": "Unity, Work, Justice",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Solomon Islands": {
        "Continent": "Oceania",
        "Currency": "Solomon Islands dollar (AUD)",
        "Languages": ["English"],
        "Cities": ["Honiara", "Gizo", "Auki", "Noro", "Munda"],
        "TimeZones": ["Solomon Islands Time (SBT)"],
        "GMTOffSets": ["+11"],
        "IndependenceDate": "July 7, 1978",
        "Motto": "To Lead is to Serve",
        "GovernmentTypes": ["parliamentary constitutional monarchy"]
    },
    "Somalia": {
        "Continent": "Africa",
        "Currency": "Somali shilling (SOS)",
        "Languages": ["Somali", "Arabic"],
        "Cities": ["Mogadishu", "Hargeisa", "Kismayo", "Bosaso", "Baidoa"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "July 1, 1960",
        "Motto": "Unity is Strength",
        "GovernmentTypes": ["federal parliamentary republic"]
    },
    "South Africa": {
        "Continent": "Africa",
        "Currency": "South African rand (ZAR)",
        "Languages": ["Afrikaans", "English", "isiNdebele", "isiXhosa", "isiZulu", "Sesotho", "Setswana", "siSwati", "Tshivenda", "Xitsonga"],
        "Cities": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
        "TimeZones": ["South Africa Standard Time (SAST)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "May 31, 1910",
        "Motto": "Unity in Diversity",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "South Korea": {
        "Continent": "Asia",
        "Currency": "South Korean won (KRW)",
        "Languages": ["Korean"],
        "Cities": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
        "TimeZones": ["Korea Standard Time (KST)"],
        "GMTOffSets": ["+9"],
        "IndependenceDate": "August 15, 1945",
        "Motto": "The Land of the Morning Calm",
        "GovernmentTypes": ["presidential republic"]
    },
    "South Sudan": {
        "Continent": "Africa",
        "Currency": "South Sudanese pound (SSP)",
        "Languages": ["English"],
        "Cities": ["Juba", "Wau", "Malakal", "Bor", "Aweil"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "July 9, 2011",
        "Motto": "Justice, Liberty, Prosperity",
        "GovernmentTypes": ["presidential republic"]
    },
    "Spain": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Spanish"],
        "Cities": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "January 1, 1492",
        "Motto": "Plus Ultra",
        "GovernmentTypes": ["parliamentary constitutional monarchy"]
    },
    "Sri Lanka": {
        "Continent": "Asia",
        "Currency": "Sri Lankan rupee (LKR)",
        "Languages": ["Sinhala", "Tamil", "English"],
        "Cities": ["Colombo", "Kandy", "Galle", "Negombo", "Jaffna"],
        "TimeZones": ["Sri Lanka Standard Time (SLST)"],
        "GMTOffSets": ["+5:30"],
        "IndependenceDate": "February 4, 1948",
        "Motto": "Unity in Diversity",
        "GovernmentTypes": ["unitary semi-presidential republic"]
    },
    "Sudan": {
        "Continent": "Africa",
        "Currency": "Sudanese pound (SDG)",
        "Languages": ["Arabic", "English"],
        "Cities": ["Khartoum", "Omdurman", "Port Sudan", "Nyala", "Kadugli"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "January 1, 1956",
        "Motto": "Unity and Freedom",
        "GovernmentTypes": ["federal presidential republic"]
    },
    "Suriname": {
        "Continent": "South America",
        "Currency": "Surinamese dollar (SRD)",
        "Languages": ["Dutch"],
        "Cities": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Brokopondo"],
        "TimeZones": ["Suriname Time (SRT)"],
        "GMTOffSets": ["-3"],
        "IndependenceDate": "November 25, 1975",
        "Motto": "Justitia, Pietas, Fides",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Sweden": {
        "Continent": "Europe",
        "Currency": "Swedish krona (SEK)",
        "Languages": ["Swedish"],
        "Cities": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "June 6, 1523",
        "Motto": "For our Sweden",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Switzerland": {
        "Continent": "Europe",
        "Currency": "Swiss franc (CHF)",
        "Languages": ["German", "French", "Italian", "Romansh"],
        "Cities": ["Zurich", "Geneva", "Basel", "Lausanne", "Bern"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "August 1, 1291",
        "Motto": "Unity is Strength",
        "GovernmentTypes": ["federal semi-direct democracy"]
    },
    "Syria": {
        "Continent": "Asia",
        "Currency": "Syrian pound (SYP)",
        "Languages": ["Arabic"],
        "Cities": ["Damascus", "Aleppo", "Homs", "Latakia", "Deir ez-Zor"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "April 17, 1946",
        "Motto": "One for All and All for One",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Taiwan": {
        "Continent": "Asia",
        "Currency": "New Taiwan dollar (TWD)",
        "Languages": ["Mandarin"],
        "Cities": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Keelung"],
        "TimeZones": ["Taiwan Time (TWT)"],
        "GMTOffSets": ["+8"],
        "IndependenceDate": "October 10, 1911",
        "Motto": "The Republic of China",
        "GovernmentTypes": ["semi-presidential republic"]
    },
    "Tajikistan": {
        "Continent": "Asia",
        "Currency": "Tajikistani somoni (TJS)",
        "Languages": ["Tajik"],
        "Cities": ["Dushanbe", "Khujand", "Kulob", "Isfara", "Qurghonteppa"],
        "TimeZones": ["Tajikistan Time (TJT)"],
        "GMTOffSets": ["+5"],
        "IndependenceDate": "September 9, 1991",
        "Motto": "We Will Build Our Future Together",
        "GovernmentTypes": ["presidential republic"]
    },
    "Tanzania": {
        "Continent": "Africa",
        "Currency": "Tanzanian shilling (TZS)",
        "Languages": ["Swahili", "English"],
        "Cities": ["Dodoma", "Dar es Salaam", "Arusha", "Mbeya", "Mwanza"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "December 9, 1961",
        "Motto": "Unity and Freedom",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Thailand": {
        "Continent": "Asia",
        "Currency": "Thai baht (THB)",
        "Languages": ["Thai"],
        "Cities": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Udon Thani"],
        "TimeZones": ["Indochina Time (ICT)"],
        "GMTOffSets": ["+7"],
        "IndependenceDate": "June 24, 1932",
        "Motto": "Nation, Religion, King",
        "GovernmentTypes": ["unitary parliamentary constitutional monarchy"]
    },
    "Timor-Leste": {
        "Continent": "Asia",
        "Currency": "United States dollar (USD)",
        "Languages": ["Tetum", "Portuguese"],
        "Cities": ["Dili", "Baucau", "Ermera", "Lautem", "Aileu"],
        "TimeZones": ["Timor-Leste Time (TLT)"],
        "GMTOffSets": ["+9"],
        "IndependenceDate": "May 20, 2002",
        "Motto": "Unity, Action, Progress",
        "GovernmentTypes": ["semi-presidential republic"]
    },
    "Togo": {
        "Continent": "Africa",
        "Currency": "West African CFA franc (XOF)",
        "Languages": ["French"],
        "Cities": ["Lomé", "Sokodé", "Kpalimé", "Tsévié", "Atakpamé"],
        "TimeZones": ["West Africa Time (WAT)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "April 27, 1960",
        "Motto": "Union, Discipline, Work",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Tonga": {
        "Continent": "Oceania",
        "Currency": "Tongan paʻanga (TOP)",
        "Languages": ["Tongan", "English"],
        "Cities": ["Nuku'alofa", "Lautoka", "Hihifo", "Vava'u", "Ha'apai"],
        "TimeZones": ["Tonga Time (TOT)"],
        "GMTOffSets": ["+13"],
        "IndependenceDate": "November 4, 1875",
        "Motto": "God and the King",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "Trinidad and Tobago": {
        "Continent": "North America",
        "Currency": "Trinidad and Tobago dollar (TTD)",
        "Languages": ["English"],
        "Cities": ["Port of Spain", "San Fernando", "Scarborough", "Chaguanas", "Arima"],
        "TimeZones": ["Atlantic Standard Time (AST)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "August 31, 1962",
        "Motto": "Together We Aspire, Together We Achieve",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "Tunisia": {
        "Continent": "Africa",
        "Currency": "Tunisian dinar (TND)",
        "Languages": ["Arabic", "French"],
        "Cities": ["Tunis", "Sfax", "Sousse", "Kairouan", "Gabès"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "March 20, 1956",
        "Motto": "Freedom, Dignity, Justice",
        "GovernmentTypes": ["semi-presidential republic"]
    },
    "Turkey": {
        "Continent": "Asia",
        "Currency": "Turkish lira (TRY)",
        "Languages": ["Turkish"],
        "Cities": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
        "TimeZones": ["Turkey Time (TRT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "October 29, 1923",
        "Motto": "Independence is my honor",
        "GovernmentTypes": ["presidential republic"]
    },
    "Turkmenistan": {
        "Continent": "Asia",
        "Currency": "Turkmenistani manat (TMT)",
        "Languages": ["Turkmen"],
        "Cities": ["Ashgabat", "Balkanabat", "Turkmenabat", "Mary", "Dashoguz"],
        "TimeZones": ["Turkmenistan Time (TMT)"],
        "GMTOffSets": ["+5"],
        "IndependenceDate": "October 27, 1991",
        "Motto": "Neutrality is Our Strength",
        "GovernmentTypes": ["presidential republic"]
    },
    "Tuvalu": {
        "Continent": "Oceania",
        "Currency": "Australian dollar (AUD)",
        "Languages": ["Tuvaluan", "English"],
        "Cities": ["Funafuti", "Nukufetau", "Nukulaelae", "Vaitupu", "Niutao"],
        "TimeZones": ["Tuvalu Time (TVT)"],
        "GMTOffSets": ["+12"],
        "IndependenceDate": "October 1, 1978",
        "Motto": "The Land of Peace",
        "GovernmentTypes": ["parliamentary democracy"]
    },
    "Uganda": {
        "Continent": "Africa",
        "Currency": "Ugandan shilling (UGX)",
        "Languages": ["English", "Swahili"],
        "Cities": ["Kampala", "Wakiso", "Gulu", "Mbarara", "Jinja"],
        "TimeZones": ["East Africa Time (EAT)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "October 9, 1962",
        "Motto": "For God and My Country",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Ukraine": {
        "Continent": "Europe",
        "Currency": "Ukrainian hryvnia (UAH)",
        "Languages": ["Ukrainian"],
        "Cities": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk"],
        "TimeZones": ["Eastern European Time (EET)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "August 24, 1991",
        "Motto": "Glory to Ukraine!",
        "GovernmentTypes": ["unitary parliamentary republic"]
    },
    "United Arab Emirates": {
        "Continent": "Asia",
        "Currency": "United Arab Emirates dirham (AED)",
        "Languages": ["Arabic"],
        "Cities": ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Ras Al Khaimah"],
        "TimeZones": ["Gulf Standard Time (GST)"],
        "GMTOffSets": ["+4"],
        "IndependenceDate": "December 2, 1971",
        "Motto": "Unity in Diversity",
        "GovernmentTypes": ["federal absolute monarchy"]
    },
    "United Kingdom": {
        "Continent": "Europe",
        "Currency": "Pound sterling (GBP)",
        "Languages": ["English"],
        "Cities": ["London", "Birmingham", "Glasgow", "Liverpool", "Manchester"],
        "TimeZones": ["Greenwich Mean Time (GMT)", "British Summer Time (BST)"],
        "GMTOffSets": ["0", "+1"],
        "IndependenceDate": "June 15, 1215",
        "Motto": "God and my right",
        "GovernmentTypes": ["constitutional monarchy"]
    },
    "United States": {
        "Continent": "North America",
        "Currency": "United States dollar (USD)",
        "Languages": ["English"],
        "Cities": ["New York City", "Los Angeles", "Chicago", "Houston", "Phoenix"],
        "TimeZones": ["Eastern Standard Time (EST)", "Central Standard Time (CST)", "Mountain Standard Time (MST)", "Pacific Standard Time (PST)"],
        "GMTOffSets": ["-5", "-6", "-7", "-8"],
        "IndependenceDate": "July 4, 1776",
        "Motto": "In God We Trust",
        "GovernmentTypes": ["federal presidential constitutional republic"]
    },
    "Uruguay": {
        "Continent": "South America",
        "Currency": "Uruguayan peso (UYU)",
        "Languages": ["Spanish"],
        "Cities": ["Montevideo", "Salto", "Paysandú", "Las Piedras", "Rivera"],
        "TimeZones": ["Uruguay Standard Time (UYT)"],
        "GMTOffSets": ["-3"],
        "IndependenceDate": "August 25, 1825",
        "Motto": "Freedom or Death",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Uzbekistan": {
        "Continent": "Asia",
        "Currency": "Uzbekistani soʻm (UZS)",
        "Languages": ["Uzbek"],
        "Cities": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Namangan"],
        "TimeZones": ["Uzbekistan Time (UZT)"],
        "GMTOffSets": ["+5"],
        "IndependenceDate": "September 1, 1991",
        "Motto": "For a Strong and Prosperous Motherland",
        "GovernmentTypes": ["presidential republic"]
    },
    "Vanuatu": {
        "Continent": "Oceania",
        "Currency": "Vanuatu vatu (VUV)",
        "Languages": ["Bislama", "English", "French"],
        "Cities": ["Port Vila", "Luganville", "Norsup", "Sola", "Lonorore"],
        "TimeZones": ["Vanuatu Time (VUT)"],
        "GMTOffSets": ["+11"],
        "IndependenceDate": "July 30, 1980",
        "Motto": "Long God Yumi Stanap",
        "GovernmentTypes": ["parliamentary republic"]
    },
    "Vatican City": {
        "Continent": "Europe",
        "Currency": "Euro (EUR)",
        "Languages": ["Latin", "Italian"],
        "Cities": ["Vatican City", "Rome", "Vatican Gardens", "St. Peter's Basilica", "Sistine Chapel"],
        "TimeZones": ["Central European Time (CET)"],
        "GMTOffSets": ["+1"],
        "IndependenceDate": "February 11, 1929",
        "Motto": "In the name of God, Amen",
        "GovernmentTypes": ["elective monarchy"]
    },
    "Venezuela": {
        "Continent": "South America",
        "Currency": "Venezuelan bolívar (VES)",
        "Languages": ["Spanish"],
        "Cities": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Ciudad Guayana"],
        "TimeZones": ["Venezuela Time (VET)"],
        "GMTOffSets": ["-4"],
        "IndependenceDate": "July 5, 1811",
        "Motto": "Damnatio Memoriae",
        "GovernmentTypes": ["federal presidential republic"]
    },
    "Vietnam": {
        "Continent": "Asia",
        "Currency": "Vietnamese đồng (VND)",
        "Languages": ["Vietnamese"],
        "Cities": ["Hanoi", "Ho Chi Minh City", "Da Nang", "Haiphong", "Can Tho"],
        "TimeZones": ["Indochina Time (ICT)"],
        "GMTOffSets": ["+7"],
        "IndependenceDate": "September 2, 1945",
        "Motto": "Independence, Freedom, Happiness",
        "GovernmentTypes": ["socialist republic"]
    },
    "Yemen": {
        "Continent": "Asia",
        "Currency": "Yemeni rial (YER)",
        "Languages": ["Arabic"],
        "Cities": ["Sanaa", "Aden", "Taiz", "Hudaydah", "Dhamar"],
        "TimeZones": ["Arabian Standard Time (AST)"],
        "GMTOffSets": ["+3"],
        "IndependenceDate": "November 30, 1967",
        "Motto": "God, Country, Revolution",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Zambia": {
        "Continent": "Africa",
        "Currency": "Zambian kwacha (ZMW)",
        "Languages": ["English"],
        "Cities": ["Lusaka", "Ndola", "Kitwe", "Livingstone", "Chingola"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "October 24, 1964",
        "Motto": "One Zambia, One Nation",
        "GovernmentTypes": ["unitary presidential republic"]
    },
    "Zimbabwe": {
        "Continent": "Africa",
        "Currency": "United States dollar (USD), Zimbabwean dollar (ZWL)",
        "Languages": ["English", "Shona", "Sindebele"],
        "Cities": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"],
        "TimeZones": ["Central Africa Time (CAT)"],
        "GMTOffSets": ["+2"],
        "IndependenceDate": "April 18, 1980",
        "Motto": "Unity, Freedom, Work",
        "GovernmentTypes": ["unitary presidential republic"]
    }
}